### ISSUE TITLE
Default key mapping has conflict with Tasklist.vim plugin.

### ISSUE THREAD

**Issue by fanlei** [habamax/vim-sendtoterm#2]
This plugin is cool. However, there is a key mapping conflict with the earlier Vim plugin Tasklist.vim with the <Leader>t occupied. Hope it could be changed or let users config by themselves.

**Comment by habamax** [comment]
Have you tried https://github.com/habamax/vim-sendtoterm#3-settings

**Comment by fanlei** [comment]
Oh, yes, I see. After adding a new map, the conflict was gone. Thank you!
